### ISSUE TITLE
WTH

### ISSUE THREAD

**Issue by 1351438** [wety-dev/jackpot-ton#1]
![Untitled](https://github.com/wety-dev/jackpot-ton/assets/40034194/feb121c5-dd06-4e24-bd49-46d6d6c9a002)
is this how the jackpots work? WTH

**Comment by 1351438** [comment]
![Untitled](https://github.com/wety-dev/jackpot-ton/assets/40034194/69d9806e-5e9f-4d2a-9b0f-59ac48b45b62)
and there is no wallet end with `KI` and you make it winner?

**Comment by wety-dev** [comment]
Website bug, fixed already
Contract works perfectly.
